name: Compile MiraiOK
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '.github/workflows/**.yml'

jobs:
  test:
    name: Test MiraiOK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Golang environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.3' # The Go version to download (if necessary) and use.

      - name: Cache Go
        id: cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
      
      - name: Test
        run: |
          echo "::warning:: Testing is not implentmented."

  build:
    name: Build MiraiOK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm]
          
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Golang environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.3' # The Go version to download (if necessary) and use.

      - name: Cache Go
        id: cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}

      - name: Build binary file
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -tags release -ldflags "-w -s" -gcflags "-l=4" -o output/binary .          

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          # A file, directory or wildcard pattern that describes what to upload
          path: "output"

